export const FETCH_BRAND_BY_CATEGORY = 'indus_more/category/FETCH_BRAND_BY_CATEGORY'
export const FETCH_BRAND_BY_CATEGORY_SUCCESS = 'indus_more/category/FETCH_BRAND_BY_CATEGORY_SUCCESS'
export const FETCH_BRAND_BY_CATEGORY_FAILED = 'indus_more/category/FETCH_BRAND_BY_CATEGORY_FAILED'

export const FETCH_OFFERS_BY_CATEGORY = 'indus_more/category/FETCH_OFFERS_BY_CATEGORY'
export const FETCH_OFFERS_BY_CATEGORY_SUCCESS =
  'indus_more/category/FETCH_OFFERS_BY_CATEGORY_SUCCESS'
export const FETCH_OFFERS_BY_CATEGORY_FAILED = 'indus_more/category/FETCH_OFFERS_BY_CATEGORY_FAILED'

export const FETCH_TRENDING_BY_CATEGORY = 'indus_more/category/FETCH_TRENDING_BY_CATEGORY'
export const FETCH_TRENDING_BY_CATEGORY_SUCCESS =
  'indus_more/category/FETCH_TRENDING_BY_CATEGORY_SUCCESS'
export const FETCH_TRENDING_BY_CATEGORY_FAILED =
  'indus_more/category/FETCH_TRENDING_BY_CATEGORY_FAILED'

export const FETCH_SUB_CATEGORY = 'indus_more/category/FETCH_SUB_CATEGORY'
export const FETCH_SUB_CATEGORY_SUCCESS = 'indus_more/category/FETCH_SUB_CATEGORY_SUCCESS'
export const FETCH_SUB_CATEGORY_FAILED = 'indus_more/category/FETCH_SUB_CATEGORY_FAILED'

export const FETCH_COMBO_OFFER_BY_CATEGORY = 'indus_more/category/FETCH_COMBO_OFFER_BY_CATEGORY'
export const FETCH_COMBO_OFFER_BY_CATEGORY_SUCCESS =
  'indus_more/category/FETCH_COMBO_OFFER_BY_CATEGORY_SUCCESS'
export const FETCH_COMBO_OFFER_BY_CATEGORY_FAILED =
  'indus_more/category/FETCH_COMBO_OFFER_BY_CATEGORY_FAILED'
export const QUANTITY_CHANGE_SUCCESS = 'indus_more/category/QUANTITY_CHANGE_SUCCESS'
